# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/life/Code/FreeRTOSV8.2.1/FreeRTOS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/life/Code/FreeRTOSV8.2.1/FreeRTOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/life/Code/FreeRTOSV8.2.1/FreeRTOS/CMakeFiles /home/life/Code/FreeRTOSV8.2.1/FreeRTOS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/life/Code/FreeRTOSV8.2.1/FreeRTOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FreeRTOS

# Build rule for target.
FreeRTOS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FreeRTOS
.PHONY : FreeRTOS

# fast build rule for target.
FreeRTOS/fast:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/build
.PHONY : FreeRTOS/fast

src/croutine.o: src/croutine.c.o

.PHONY : src/croutine.o

# target to build an object file
src/croutine.c.o:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/croutine.c.o
.PHONY : src/croutine.c.o

src/croutine.i: src/croutine.c.i

.PHONY : src/croutine.i

# target to preprocess a source file
src/croutine.c.i:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/croutine.c.i
.PHONY : src/croutine.c.i

src/croutine.s: src/croutine.c.s

.PHONY : src/croutine.s

# target to generate assembly for a file
src/croutine.c.s:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/croutine.c.s
.PHONY : src/croutine.c.s

src/event_groups.o: src/event_groups.c.o

.PHONY : src/event_groups.o

# target to build an object file
src/event_groups.c.o:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/event_groups.c.o
.PHONY : src/event_groups.c.o

src/event_groups.i: src/event_groups.c.i

.PHONY : src/event_groups.i

# target to preprocess a source file
src/event_groups.c.i:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/event_groups.c.i
.PHONY : src/event_groups.c.i

src/event_groups.s: src/event_groups.c.s

.PHONY : src/event_groups.s

# target to generate assembly for a file
src/event_groups.c.s:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/event_groups.c.s
.PHONY : src/event_groups.c.s

src/heap_3.o: src/heap_3.c.o

.PHONY : src/heap_3.o

# target to build an object file
src/heap_3.c.o:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/heap_3.c.o
.PHONY : src/heap_3.c.o

src/heap_3.i: src/heap_3.c.i

.PHONY : src/heap_3.i

# target to preprocess a source file
src/heap_3.c.i:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/heap_3.c.i
.PHONY : src/heap_3.c.i

src/heap_3.s: src/heap_3.c.s

.PHONY : src/heap_3.s

# target to generate assembly for a file
src/heap_3.c.s:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/heap_3.c.s
.PHONY : src/heap_3.c.s

src/list.o: src/list.c.o

.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/list.c.s
.PHONY : src/list.c.s

src/port.o: src/port.c.o

.PHONY : src/port.o

# target to build an object file
src/port.c.o:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/port.c.o
.PHONY : src/port.c.o

src/port.i: src/port.c.i

.PHONY : src/port.i

# target to preprocess a source file
src/port.c.i:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/port.c.i
.PHONY : src/port.c.i

src/port.s: src/port.c.s

.PHONY : src/port.s

# target to generate assembly for a file
src/port.c.s:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/port.c.s
.PHONY : src/port.c.s

src/queue.o: src/queue.c.o

.PHONY : src/queue.o

# target to build an object file
src/queue.c.o:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/queue.c.o
.PHONY : src/queue.c.o

src/queue.i: src/queue.c.i

.PHONY : src/queue.i

# target to preprocess a source file
src/queue.c.i:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/queue.c.i
.PHONY : src/queue.c.i

src/queue.s: src/queue.c.s

.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.c.s:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/queue.c.s
.PHONY : src/queue.c.s

src/tasks.o: src/tasks.c.o

.PHONY : src/tasks.o

# target to build an object file
src/tasks.c.o:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/tasks.c.o
.PHONY : src/tasks.c.o

src/tasks.i: src/tasks.c.i

.PHONY : src/tasks.i

# target to preprocess a source file
src/tasks.c.i:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/tasks.c.i
.PHONY : src/tasks.c.i

src/tasks.s: src/tasks.c.s

.PHONY : src/tasks.s

# target to generate assembly for a file
src/tasks.c.s:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/tasks.c.s
.PHONY : src/tasks.c.s

src/timers.o: src/timers.c.o

.PHONY : src/timers.o

# target to build an object file
src/timers.c.o:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/timers.c.o
.PHONY : src/timers.c.o

src/timers.i: src/timers.c.i

.PHONY : src/timers.i

# target to preprocess a source file
src/timers.c.i:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/timers.c.i
.PHONY : src/timers.c.i

src/timers.s: src/timers.c.s

.PHONY : src/timers.s

# target to generate assembly for a file
src/timers.c.s:
	$(MAKE) -f CMakeFiles/FreeRTOS.dir/build.make CMakeFiles/FreeRTOS.dir/src/timers.c.s
.PHONY : src/timers.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... FreeRTOS"
	@echo "... src/croutine.o"
	@echo "... src/croutine.i"
	@echo "... src/croutine.s"
	@echo "... src/event_groups.o"
	@echo "... src/event_groups.i"
	@echo "... src/event_groups.s"
	@echo "... src/heap_3.o"
	@echo "... src/heap_3.i"
	@echo "... src/heap_3.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/port.o"
	@echo "... src/port.i"
	@echo "... src/port.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/tasks.o"
	@echo "... src/tasks.i"
	@echo "... src/tasks.s"
	@echo "... src/timers.o"
	@echo "... src/timers.i"
	@echo "... src/timers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

